### ISSUE TITLE
NG cockpit is used to manage customers & organizations entities

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_igor#11]
As a **content manager**
I want to be able to change customers and organizations attributes in more modern way
So that backoffice extension is added to B2C accelerator

**AC:**
1. Organizations node is added to backoffice objects tree
2. Organizations manager is able to perform CRUD-operations with organizations & customers via backoffice web-page.

*Tips:*
https://wiki.hybris.com/display/release5/Include+-+Create+a+Custom+Backoffice+Extension 
https://wiki.hybris.com/display/tr52/Trail+~+Customizing+Backoffice+-+Cockpit+NG

**Comment by ibiliaiev** [comment]
![issue_11_1](https://cloud.githubusercontent.com/assets/7289951/17525757/d7e1dd1a-5e6c-11e6-88a6-c05d68ef6bde.png)
![issue_11_2](https://cloud.githubusercontent.com/assets/7289951/17525758/d7e2246e-5e6c-11e6-8456-25c0d208745f.png)
![issue_11_3](https://cloud.githubusercontent.com/assets/7289951/17525756/d7e1c2f8-5e6c-11e6-93c2-c27ef3745d76.png)
![issue_11_4](https://cloud.githubusercontent.com/assets/7289951/17525759/d7e4e2da-5e6c-11e6-8f7f-44b947cff3ad.png)
![issue_11_5](https://cloud.githubusercontent.com/assets/7289951/17525760/d7e5b994-5e6c-11e6-97e7-6d11402285f9.png)
Few Screenshots

**Comment by ibiliaiev** [comment]
Issue has been completed. Bugs in HMC where fixed :)
