### ISSUE TITLE
Editing Organizations in HMC

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_igor#7]
As a **content manager**
I want Organizations node be available in hMC 
So that Customer’s Organizations can be edited, created and deleted

**AC:**
HMC has a view for editing Organizations properties
User View in HMC has an attribute to assign or remove an organization

*Technical tips:*
https://wiki.hybris.com/display/tr51/Trail+~+Integration+in+the+hMC

**Comment by ibiliaiev** [comment]
![traininghmc](https://cloud.githubusercontent.com/assets/7289951/17367443/8f639fe8-5998-11e6-91f2-799c91dd3404.png)
Issue has been done. New extension 'traininghmc' is committed.
